### ISSUE TITLE
关于RSDet的两个模块

### ISSUE THREAD

**Issue by xyl-507** [Zhao-Tian-yi/RSDet#13]
@Zhao-Tian-yi 
感谢作者的杰出贡献！
请问一下，RSDet的两个模块在代码中什么地方？自己找了很久没找到。

谢谢！

**Comment by Zhao-Tian-yi** [comment]
本文档当前开源了基于mmdetection的双流视觉检测框架，其中有一些方法前期试验阶段的模块。但是因本论文还在投稿修改状态中，所以没有更新到论文中所有的版本代码，当此论文被接收后，会整理代码组织方法的开源

**Comment by Zhao-Tian-yi** [comment]
在审其他期刊的稿件过程中，已经发现了严重抄袭现象，为保护论文以及作者权益，请您理解。

**Comment by xyl-507** [comment]
> 在审其他期刊的稿件过程中，已经发现了严重抄袭现象，为保护论文以及作者权益，请您理解。

好的，谢谢作者。期待其顺利发表。

**Comment by bloomingvision** [comment]
所以，现在已经发表了，可以告诉两个模块的具体位置吗？
