### ISSUE TITLE
配对数据集的组织形式，mask,的设置及训练用到的配置文件（14th or 15th）

### ISSUE THREAD

**Issue by liting1018** [Zhao-Tian-yi/RSDet#6]
作者大大好：
非常感谢您开源的代码，但我对于您提供的代码有一些疑问。
（1）关于配对数据集的组织形式，我看您代码里设置的dict(type='LoadAnnotations', with_bbox=True, with_mask=True)，您这里是用到了mask信息嘛，我不太清楚您这里的mask设置，我这边的情况是设置with_mask=True时会报错，我修改为False能够跑通。
（2）对于FLIR数据集来说，您提供的训练配置文件包括了configs/fusion/RSDet/faster_rcnn_r50_common_unique_FLIR_14th.py和configs/fusion/RSDet/faster_rcnn_r50_common_unique_FLIR_15th.py，请问您论文中的结果是对应哪个配置文件呢？

期待能得到您的回复，感谢感谢！

**Comment by liting1018** [comment]
我尝试采用配置文件configs/fusion/RSDet/faster_rcnn_r50_common_unique_FLIR_14th.py来训练，复现的结果和您论文中的指标差距较大，我测试的结果是bbox_mAP_copypaste: 0.322 0.686 0.252 0.218 0.374 0.401。不知道我哪里操作有问题，期望您的回复！
祝好！

**Comment by Zhao-Tian-yi** [comment]
1

**Comment by wanganrui-nj** [comment]
> 作者大大好： 非常感谢您开源的代码，但我对于您提供的代码有一些疑问。 （1）关于配对数据集的组织形式，我看您代码里设置的dict(type='LoadAnnotations', with_bbox=True, with_mask=True)，您这里是用到了mask信息嘛，我不太清楚您这里的mask设置，我这边的情况是设置with_mask=True时会报错，我修改为False能够跑通。 （2）对于FLIR数据集来说，您提供的训练配置文件包括了configs/fusion/RSDet/faster_rcnn_r50_common_unique_FLIR_14th.py和configs/fusion/RSDet/faster_rcnn_r50_common_unique_FLIR_15th.py，请问您论文中的结果是对应哪个配置文件呢？
> 
> 期待能得到您的回复，感谢感谢！

![image](https://github.com/Zhao-Tian-yi/RSDet/assets/71579899/233e0851-2a12-4d64-a30f-71f1e7639dcf)
 请问你遇到过这种情况嘛？

**Comment by Zhao-Tian-yi** [comment]
（1）mask设置为False就可以，没有使用mask信息，因为我改的时候源代码是这样写的，可能在转换数据集的时候，我使用的脚本生成了mask的参数，所以我没有报错，也就没有注意更改这个参数。（2）您可以使用14th的配置文件，可以达到不错的效果，但本文仍然再审，若被接受后，有时间我会对本库代码进行更新。（3）您的截图可以进行debug找到对应的位置，那里有被注释掉的代码，根据数据集更换一下。

**Comment by wanganrui-nj** [comment]
> （1）mask设置为False就可以，没有使用mask信息，因为我改的时候源代码是这样写的，可能在转换数据集的时候，我使用的脚本生成了mask的参数，所以我没有报错，也就没有注意更改这个参数。（2）您可以使用14th的配置文件，可以达到不错的效果，但本文仍然再审，若被接受后，有时间我会对本库代码进行更新。（3）您的截图可以进行debug找到对应的位置，那里有被注释掉的代码，根据数据集更换一下。

您好，我把`self.pool`替换为`FLIR`数据集的后报了这个错
![image](https://github.com/Zhao-Tian-yi/RSDet/assets/71579899/5a02950a-2d35-4acc-be0c-47bffa53c9e4)
![image](https://github.com/Zhao-Tian-yi/RSDet/assets/71579899/cb444c1e-cfd9-4f73-ae62-6f93e4c00ed2)

**Comment by wanganrui-nj** [comment]
> > （1）mask设置为False就可以，没有使用mask信息，因为我改的时候源代码是这样写的，可能在转换数据集的时候，我使用的脚本生成了mask的参数，所以我没有报错，也就没有注意更改这个参数。（2）您可以使用14th的配置文件，可以达到不错的效果，但本文仍然再审，若被接受后，有时间我会对本库代码进行更新。（3）您的截图可以进行debug找到对应的位置，那里有被注释掉的代码，根据数据集更换一下。
> 
> 您好，我把`self.pool`替换为`FLIR`数据集的后报了这个错 ![image](https://private-user-images.githubusercontent.com/71579899/335975831-5a02950a-2d35-4acc-be0c-47bffa53c9e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDAwNzIsIm5iZiI6MTcxNzM5OTc3MiwicGF0aCI6Ii83MTU3OTg5OS8zMzU5NzU4MzEtNWEwMjk1MGEtMmQzNS00YWNjLWJlMGMtNDdiZmZhNTNjOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA3MjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNzM2MjYxODZlYmExOTM0N2IwZjI0OGY2MjFmNGJiY2RlOWNiNzA2ZmJlMzliNWZkNGFlODJmZjViNWMxMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8MXq_tbsH1xa5Le7WI2nCdj_z3nhHLjCPqEWvUEN8hQ) ![image](https://private-user-images.githubusercontent.com/71579899/335975872-cb444c1e-cfd9-4f73-ae62-6f93e4c00ed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDAwNzIsIm5iZiI6MTcxNzM5OTc3MiwicGF0aCI6Ii83MTU3OTg5OS8zMzU5NzU4NzItY2I0NDRjMWUtY2ZkOS00ZjczLWFlNjItNmY5M2U0YzAwZWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA3MjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNzdmNGM3MjUxY2NiMjYwYTI2MmM5ODFmM2ExZDBiNGZmZjg5YjMyMTY1MWIxNjU1OTFiOTQ5ZjhmZGJmY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fc9mTCTAo75ZAizvsPNwcqpqVpUDxFrphFGeI09QQzY)

不好意思，是我类别设置的问题，已经解决了，感谢您的工作和您耐心的回复，希望能看到您更多杰出的工作！

**Comment by wanganrui-nj** [comment]
> （1）mask设置为False就可以，没有使用mask信息，因为我改的时候源代码是这样写的，可能在转换数据集的时候，我使用的脚本生成了mask的参数，所以我没有报错，也就没有注意更改这个参数。（2）您可以使用14th的配置文件，可以达到不错的效果，但本文仍然再审，若被接受后，有时间我会对本库代码进行更新。（3）您的截图可以进行debug找到对应的位置，那里有被注释掉的代码，根据数据集更换一下。

另外请问一下修改了`kernel_size`后`self.IA_fc11`和`self.IA_fc21`中的`in_features`也要做相应的修改嘛？
![image](https://github.com/Zhao-Tian-yi/RSDet/assets/71579899/d9ae1f4c-5824-4bd4-b04e-c010a11b051f)
